### ISSUE TITLE
CKANパーツのURLについてのヘルプが出せない

### ISSUE THREAD

**Issue by kaosf** [shirasagi/opendata#92]
![ckan-help](https://cloud.githubusercontent.com/assets/1495128/12338449/f4842e04-bb52-11e5-8acb-4c1f882f42f9.png)

この位置にヘルプメッセージ (URLはどういうものを入力すればいいのかの説明) を出したいのですが，

`config/locales/ckan/ja.yml`

に

``` yaml
ja:
  tooltip:
    ckan/addon/status:
      ckan_url:
        - ヘルプメッセージ
```

と書いても出てきません．

どうすれば良いでしょうか？
